### ISSUE TITLE
chatgpt error 

### ISSUE THREAD

**Issue by BenCos17** [Skylark95/skylark95-cogs#3]
```#57 [2024-03-04 18:44:25] ERROR [discord.client] Ignoring exception in on_message.

Traceback (most recent call last):
File "{HOME}/.local/share/Red-DiscordBot/data/jarvis/cogs/CogManager/cogs/chatgpt/chatgpt.py", line 103, in call_api
response = openai.ChatCompletion.create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "{HOME}/.local/share/Red-DiscordBot/data/jarvis/cogs/Downloader/lib/openai/lib/_old_api.py", line 39, in __call__
raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "{HOME}/redenv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
await coro(*args, **kwargs)
File "{HOME}/.local/share/Red-DiscordBot/data/jarvis/cogs/CogManager/cogs/chatgpt/chatgpt.py", line 52, in on_message
await self.do_chatgpt(ctx)
File "{HOME}/.local/share/Red-DiscordBot/data/jarvis/cogs/CogManager/cogs/chatgpt/chatgpt.py", line 76, in do_chatgpt
reply = await self.call_api(
^^^^^^^^^^^^^^^^^^^^
File "{HOME}/.local/share/Red-DiscordBot/data/jarvis/cogs/CogManager/cogs/chatgpt/chatgpt.py", line 113, in call_api
except openai.error.APIError as e:
^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error' #57 [2024-03-04 18:44:25] ERROR [discord.client] Ignoring exception in on_message.     ``` 





had this error show up on chatgpt today with your cog

**Comment by Skylark95** [comment]
Looks like it needs a dependency update. I should be able to get around to this in a few days.

**Comment by BenCos17** [comment]
Thanks

**Comment by Skylark95** [comment]
This has been fixed in the latest version.

Updating the `openai` package on your server unfortunately will require manual intervention at it appears the bot doesn't handle this for you.

Follow the instructions to activate your virtual environment from the [Installing Red instructions](https://docs.discord.red/en/stable/install_guides/index.html) and then run the following command:

- `python -m pip install -U openai`

Restart the bot. Then install the update using bot commands:

- `[p] repo update`
- `[p] cog update chatgpt`

**Comment by BenCos17** [comment]
thanks 
I'll test it rn

**Comment by BenCos17** [comment]
works perfectly 
thanks
